# Generated by Django 2.1.5 on 2019-01-14 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('q', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('ans', models.CharField(default=None, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='leaderboard',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('score', models.CharField(default=None, max_length=150, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now=True, null=True)),
                ('finished_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('q_no', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(default=None, max_length=150, null=True)),
                ('content', models.TextField(default=None, null=True)),
            ],
        ),
    ]
