# Generated by Django 2.1.2 on 2019-01-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='finished_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
