# Generated by Django 2.1.2 on 2019-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190121_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
