# Generated by Django 2.1.2 on 2019-01-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20190121_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
